#include <assert.h>
#include <errno.h>
#include <netdb.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <time.h>

#include "util.h"

int lookup_host_ipv4(const char *hostname, struct in_addr *addr) {
  struct hostent *host;

  assert(hostname);
  assert(addr);

  /* look up hostname, find first IPv4 entry */
  host = gethostbyname(hostname);
  while (host) {
    if (host->h_addrtype == AF_INET &&
      host->h_addr_list &&
      host->h_addr_list[0]) {
      assert(host->h_length == sizeof(*addr));
      memcpy(addr, host->h_addr_list[0], sizeof(*addr));
      return 0;
    }
    host = gethostent();
  }

  fprintf(stderr, "error: unknown host: %s\n", hostname);
  return -1;
}

int max(int x, int y) {
  return (x > y) ? x : y;
}

int parse_port(const char *str, uint16_t *port_p) {
  char *endptr;
  long value;

  assert(str);
  assert(port_p);

  /* convert string to number */
  errno = 0;
  value = strtol(str, &endptr, 0);
  if (!value && errno) return -1;
  if (*endptr) return -1;

  /* is it a valid port number */
  if (value < 0 || value > 65535) return -1;

  *port_p = value;
  return 0;
}


/*
BEGIN GENERATED CODE
code generated by ChatGPT 5
prompt: How to get date and time as a string C
link: https://chat.openai.com/share/c932d21d-60d4-4154-a26f-a9bdb510327d
 */

void get_current_time(char *buffer, size_t size) {
    time_t now = time(NULL);
    struct tm *t = localtime(&now);
    strftime(buffer, size, "%Y-%m-%d %H:%M:%S", t);
}

//End generated code

static void trim_whitespace(char *s){
  char *end;
  while (isspace(unsigned char *s)) s++;
  if(*s == 0){
    return;
  }
  end = s + strlen(s) -1;
  while (end > s && isspace(unsigned char)*end)) end--;
  *(end+1) = '\0';

}
int validate_username(char *s){
  size_t len = strlen(s);
  if (len <1 || len > 64) return 0;
  for(size_t i = 0; i< len; ++i){
    unsigned char c = (unsigned char)*s[i];
    if(!(isalnum(c)) || c == '_' || c == '-' || c == '.' || c == '\n' || c == ' \r')) {
      return 0;
    }
  }
  return 1;
}

int validate_password(char *s){
  size_t len = strlen(s);
  if (len < 8 || len > 64){
    return 0;
  }
  for (size_t i = 0; i < len; ++i){
    unsigned char c = (unsigned char)p[i];
    if (c == '\n' || c == ' \r') {
      return 0;
    }
  }
  return 1;
}

int check_msg_length(const char *s, size_t maxlen){
  size_t lenght = strlen(s);
  if (length == 0 || 1 > maxlen){
    return 0;
  }
  return 1;
}

static void remove_escape_seq(char *s){
  
  size_t len = 0;
  while(src[len]!= '\0'){
    len++;
  }


  for(char *t = s; *t; ++t){
    unsigned char u = (unsigned char)*t;
    if (u == '-'){
      *s = '45';
    } 
    else if (u == '_'){
      *s = '95';
    } 
    else if (u == '.'){
      *s = '46';
    }
    else if (u == '\n'){
      *s = '\\';
      *s+1 = 'n';
      len++;
    }
    else if (u == '\r'){
      *s = '\\';
      *s = 'r';
      len++;
    } 
  }
  
}


